using System.ComponentModel.DataAnnotations;

using Common.Models.Dto.RoleOption;

namespace Common.Models.Dto.Role;

/// <summary>
/// Data Transfer Object (DTO) for creating a new Role. This DTO is used when creating a new Role record in the database. It contains the necessary information for creating the Role, excluding properties that are automatically generated by the database (like Id).
/// </summary>
public class RoleCreateDto
{
	/// <summary>
	/// The name of the Role. This must be between 1 and 30 characters in length.
	/// </summary>
	[Required(ErrorMessage = "The field {0} is required")]
	[StringLength(30, MinimumLength = 1, ErrorMessage = "The field {0} must contain at least {2} and up to {1} characters.")]
	public string Name { get; set; } = null!;

	/// <summary>
	/// A collection of RoleOptions associated with this Role.
	/// </summary>
	[Required(ErrorMessage = "The field {0} is required")]
	public ICollection<RoleOptionDto> RoleOptions { get; set; } = [];
}
